"""
011. Spot the Difference

This question is asked by Google.
You are given two strings, s and t which only consist of lowercase letters.
t is generated by shuffling the letters in s as well as potentially adding
an additional random character.
Return the letter that was randomly added to t if it exists, otherwise, return ’‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''
"""


def spot_the_difference(s: str, t: str) -> str:
    """
    Solution: Hashmap of s and t
    Time Complexity: O(m + n)  # n is length of t
    Space Complexity: O(m + n)  # m is length of s
    """
    hmap: dict = {}

    for c in s:
        hmap[c] = hmap.get(c, 0) + 1

    for c in t:
        hmap[c] = hmap.get(c, 0) + 1

    for k, v in hmap.items():
        if v % 2 != 0:
            return k

    return ""
