# Generated by Django 5.1.5 on 2025-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='live',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
